import LegalPage from "@/components/LegalPage";

const sections = [
  {
    id: "intro",
    heading: "Introduction",
    body: [
      "Aatreya Infotech Systems LLP (“Aatreya”, “we”, “us”) is committed to protecting the privacy and confidentiality of data belonging to temple administrations, devotees, government departments, and website visitors.",
      "This Privacy Policy explains what information we collect, how we use it, and the choices you have. It applies to our websites (aatreya.co.in, aatreyanews.in, aatreya.org, aatreyaomnicloud.com), mobile applications, and cloud platforms.",
    ],
  },
  {
    id: "information-we-collect",
    heading: "Information We Collect",
    body: [
      "We collect only what is necessary to deliver our services. This may include:",
      [
        "Contact details submitted through our website forms (name, email, phone, organization, message).",
        "Client account information provided by temple administrations and government departments.",
        "Operational data generated by our platforms (queue tokens, digital ID passes, QR verification logs, transaction records).",
        "Technical data such as IP address, device type, browser, and cookies for security and analytics.",
        "Photographs and identity data captured through Photo Ticketing and Digital ID Pass systems — processed strictly for the temple / departmental purpose for which they were collected.",
      ],
    ],
  },
  {
    id: "how-we-use",
    heading: "How We Use Information",
    body: [
      "We use collected information to:",
      [
        "Provide, operate, and improve our software solutions.",
        "Respond to enquiries, provide technical support, and communicate service updates.",
        "Comply with temple administration and government reporting requirements.",
        "Prevent fraud, misuse, and unauthorised access to our platforms.",
        "Send transactional notifications via WhatsApp Business, SMS, or email — where explicitly authorised by the client.",
      ],
    ],
  },
  {
    id: "sharing",
    heading: "Sharing of Information",
    body: [
      "We do not sell your personal information. We share information only in these limited circumstances:",
      [
        "With the client temple / department that owns the deployment.",
        "With trusted infrastructure providers (Microsoft Azure, WhatsApp Business API, email providers) strictly to operate our services.",
        "When required by law, court order, or government authority.",
      ],
    ],
  },
  {
    id: "security",
    heading: "Data Security",
    body: [
      "We follow enterprise-grade security practices — including TLS encryption, role-based access control, audit logging, and secure cloud infrastructure on Microsoft Azure.",
      "While no system can be perfectly secure, we take reasonable and industry-standard measures to protect data entrusted to us.",
    ],
  },
  {
    id: "retention",
    heading: "Data Retention",
    body: [
      "We retain information for as long as required to provide our services, meet legal and audit obligations, and honour the retention terms defined in each client Work Order.",
      "Upon termination of an engagement, we return or securely delete client data in accordance with the Work Order.",
    ],
  },
  {
    id: "cookies",
    heading: "Cookies & Analytics",
    body: [
      "Our websites use minimal cookies and analytics to understand traffic and improve the user experience. You may disable cookies in your browser, though some features may not function correctly.",
    ],
  },
  {
    id: "rights",
    heading: "Your Rights",
    body: [
      "Depending on applicable law, you may have the right to access, correct, or delete personal information we hold about you, and to withdraw consent to communications.",
      "To exercise these rights, please contact us at info@aatreya.co.in.",
    ],
  },
  {
    id: "childrens",
    heading: "Children's Data",
    body: [
      "Our services are directed at temple administrations, government departments, and enterprise clients. We do not knowingly collect personal information from children under 13.",
    ],
  },
  {
    id: "updates",
    heading: "Updates to this Policy",
    body: [
      "We may update this Privacy Policy periodically. Material changes will be reflected here with a new “Last updated” date. Continued use of our services indicates acceptance of the updated policy.",
    ],
  },
  {
    id: "contact-privacy",
    heading: "Contact",
    body: [
      "For any privacy questions or requests, contact us at:",
      "Aatreya Infotech Systems LLP, D. No. 2-105, Edlapalli, Tenali – 522211, Andhra Pradesh, India. Phone: +91 86442 97366. Email: info@aatreya.co.in",
    ],
  },
];

export default function Privacy() {
  return (
    <LegalPage
      testid="page-privacy"
      eyebrow="Legal"
      title="Privacy Policy"
      updated="04 December 2025"
      sections={sections}
    />
  );
}
